[pytest]
testpaths = tests
addopts = -v --alluredir=allure-results
markers =
    smoke: smoke tests for critical user flows
    smoke_reset: smoke test for reset flow
    smoke_dashboard: smoke dashboard page
